name: Generate Index Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Generate index.html
        run: |
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>H:Mods</title>
          <link href="https://github.com/C0dwiz/H.Modules/raw/assets/style.css" rel="stylesheet" />
          </head>
          <body>
          <div class="container">
          <h1>H:Mods modules</h1>
          <ul class="module-list">
          $(for file in *.py; do echo " <li class="module-item"><a href=\"$file\" class="module-link">$file</a></li>"; done)
          </ul>
          </div>
          </body>
          </html>
          EOF
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .
