name: Generate Index Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Generate index.html
        run: |
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html>
          <head><title>My Python Modules</title></head>
          <body>
          <h1>My Python Modules</h1>
          <ul>
          $(for file in *.py; do echo "  <li><a href=\"$file\">$file</a></li>"; done)
          </ul>
          </body>
          </html>
          EOF
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .
